Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "private_network", ip: "192.168.1.10"
    mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    mysql.vm.provider "virtualbox" do |vb|
      vb.name = "mysql"
    end

    mysql.vm.provision "shell", path: "./scripts/mysql_setup.sh"
  end

end
